class Const(object):
    __slots__ = ()
    
    CONST_FULL_CONFIGURATION = "FULL CONFIGURATION"
    CONST_FULL_EXECUTION = "FULL EXECUTION"
    
    CONST_EXTENSION_CREATTION = "EXTENSION CREATION"
    CONST_EXTENSION_EXECUTION = "EXTENSION EXECUTION"
    
    #CONST_DELTA_CREATTION = "DELTA CREATION"
    CONST_DELTA_CONFIGURATION = "DELTA CONFIGURATION"
    CONST_DELTA_EXECUTION = "DELTA EXECUTION"
    
    CONST_DELETIONS_CREATTION = "DELETION CREATION"
    CONST_DELETIONS_EXECUTION = "DELETION EXECUTION"

    CONST_TIMEZONE_CREATTION = "TIMEZONE CREATION"
    CONST_TIMEZONE_EXECUTION = "TIMEZONE EXECUTION"

    CONST_PERF_VIEW_CREATTION = "PERF. VIEW CREATION"
    CONST_PERF_VIEW_EXECUTION = "PERF. VIEW EXECUTION"

    CONST_ANON_VIEW_CREATTION = "ANON. VIEW CREATION"
    CONST_ANON_VIEW_EXECUTION = "ANON. VIEW EXECUTION"

    CONST_USECASE_CREATTION = "USE CASE CREATION"
    CONST_USECASE_EXECUTION = "USE CASE EXECUTION"
    
    CONST_CONFIG_WRONG = 0
    CONST_CONFIG_USECASE = 1
    CONST_CONFIG_USECASE_SYSTEMS = 2
    CONST_CONFIG_SYSTEMS_TABLES = 3
    CONST_CONFIG_SYSTEMS = 4
    
    CONST_STEP_NONE = 0
    CONST_STEP_ID_FULL = 1
    CONST_STEP_ID_EXTENSION = 2
    CONST_STEP_ID_DELTA = 3
    CONST_STEP_ID_DELETIONS = 4
    CONST_STEP_ID_TIMEZONE = 5
    CONST_STEP_ID_PERF_VIEW = 6
    CONST_STEP_ID_ANON_VIEW = 7
    CONST_STEP_ID_USECASE = 8
    
    CONST_STEP_DESCRIPTION_NONE = "NONE"
    CONST_STEP_DESCRIPTION_FULL = "FULL"
    CONST_STEP_DESCRIPTION_EXTENSION = "EXTENSIONS"
    CONST_STEP_DESCRIPTION_DELTA = "DELTA"
    CONST_STEP_DESCRIPTION_DELETIONS = "DELETIONS"
    CONST_STEP_DESCRIPTION_TIMEZONE = "TIMEZONE"
    CONST_STEP_DESCRIPTION_PERF_VIEW = "PERF. VIEW"
    CONST_STEP_DESCRIPTION_ANON_VIEW = "ANON. VIEW"
    CONST_STEP_DESCRIPTION_USECASE = "USECASE"
    
    #CONST_DEBUG_LEVEL_NONE = 0
    #CONST_DEBUG_LEVEL_INFO = 1
    #CONST_DEBUG_LEVEL_DEBUG = 2

    CONST_CELONIS_TEAM = "bosch.eu-4"

    CONST_STEP_DESCRIPTION = "STEP --> "
    CONST_ACTIVITY_DESCRIPTION = "ACTIVITY --> "

    CONST_STANDARD_TIMEZONE = 'Timezone View New'

    # Modes for Data Pipeline Execution    
    #   RECREATE: deletes all existing objects and recreate them (only valid if only system given)
    #   UPDATE: deletes all per parameter given objects. New objects will be created as well
    #   ADD: Only add new objects    
    CONST_MODE_ADD = 1001
    CONST_MODE_UPDATE = 1002
    CONST_MODE_RECREATE = 1003

    CONST_MODE_DESCRIPTION_RECREATE = "RECREATE"
    CONST_MODE_DESCRIPTION_ADD = "ADD"
    CONST_MODE_DESCRIPTION_UPDATE = "UPDATE"


    CONST_DUMMY_OBJECT = 'DUMMYOBJECT_ID'
    
